exclude_paths:
  - spec/dummy/

detectors:
  TooManyStatements:
    max_statements: 10
  FeatureEnvy:
    exclude:
      - EventLoggerRails::Extensions::Loggable#details_for_trace
  UtilityFunction:
    exclude:
      - EventLoggerRails::Extensions::Loggable#details_for_trace
      - EventLoggerRails::EventLogger#structured_output
