exclude_paths:
  - spec/dummy/

detectors:
  TooManyStatements:
    max_statements: 10
  FeatureEnvy:
    exclude:
      - EventLoggerRails::Extensions::Loggable#log_event
      - EventLoggerRails::Middleware::CaptureRequestDetails#call
  LongParameterList:
    exclude:
      - EventLoggerRails::Formatters::JSON#call
  ManualDispatch:
    exclude:
      - EventLoggerRails::Output#initialize
  MissingSafeMethod:
    exclude:
      - EventLoggerRails::Event
  UtilityFunction:
    exclude:
      - EventLoggerRails::Formatters::JSON#call
      - EventLoggerRails::Output#application_data
