require:
  - rubocop-performance
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
Naming/RescuedExceptionsVariableName:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 4
